export default function EditModalCandidate() {
    return (<>
        <tr>
            <td>
                <input
                    type="text"
                    placeholder="Имя Фамилия"
                    name="fullName"></input>
            </td>

        </tr>
        <tr>
            <td>
                <input
                    type="text"
                    placeholder="profession"
                    name="profession"></input>
            </td>
        </tr>
        <tr>
            <td>
                <input
                    type="text"
                    placeholder="address"
                    name="address"></input>
            </td>
        </tr>
        <tr>
            <td>
                <input
                    type="text"
                    placeholder="phoneNumber"
                    name="phoneNumber"></input>
            </td>
        </tr>
        <tr>
            <td>
                <a href="https://t.me/">
                    <input
                    type="text"
                    placeholder="telegram"
                    name="telegram"></input>
                </a>
            </td>
        </tr>
        <tr>
            <td>
                <input
                    type="text"
                    placeholder="email"
                    name="email"></input>
            </td>
        </tr>
        <tr>
            <td>
                <input
                    type="text"
                    placeholder="urls"
                    name="urls"></input>
            </td>
        </tr>
        <tr>
            <td>
                <h4>О себе:</h4>
                <input
                    type="text"
                    placeholder="profile"
                    name="profile"></input>
            </td>
        </tr>
        <tr>
            <td>
                <h4>Опыт:</h4>
                <input
                    type="text"
                    placeholder="experience"
                    name="experience"></input>
            </td>
        </tr>
        <tr>
            <td>
                <h4>Образование:</h4>
                <input
                    type="text"
                    placeholder="education"
                    name="education"></input>
            </td>
        </tr>
        <tr>
            <td>
                <h4>Навыки:</h4>
                <input
                    type="text"
                    placeholder="skills"
                    name="skills"></input>
            </td>
        </tr>
        <tr>
            <td>
                <h4>Языки:</h4>
                <input
                    type="text"
                    placeholder="languages"
                    name="languages"></input>
            </td>
        </tr>
        <tr>
            <td>
                <h4>Сертификаты:</h4>
                <input
                    type="text"
                    placeholder="sertificates"
                    name="sertificates"></input>
            </td>
        </tr>
        <tr>
            <td>
                <h4>Прочее:</h4>
                <input
                    type="text"
                    placeholder="other"
                    name="other"></input>
            </td>
        </tr>
    </>)
}